name: log gh env vars

on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]

jobs:
  check-assign-action:
    runs-on: ubuntu-latest
    steps:
    - name: log a bunch of stuff.
      run: |
        echo "github repository: $(basename ${{ github.repository }})"
        echo "github user: $(dirname ${{ github.repository }})"
        echo "github event space: $(jq ${{ github.event }})"
