name: log gh env vars

on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]

jobs:
  check-assign-action:
    runs-on: ubuntu-latest
    steps:
    - name: log a bunch of stuff.
      run: |
        echo "github repository: ${{ github.repository }}"
        echo "github user: ${{ github.user }}"
        echo "github even space: ${{ github.event }}"
